# Generated by Django 3.2.5 on 2021-07-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetsPythonTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Timestamp')),
                ('python_tips', models.TextField(verbose_name='Python Tips')),
                ('twitter_id', models.CharField(max_length=200, verbose_name='Your name or Twitter id')),
                ('email', models.EmailField(max_length=254, verbose_name='Your email')),
            ],
        ),
    ]
